// pages/src/app/manager/page.tsx
import DownloadSystem from "@/components/DownloadSystem";
import { managerBuilds } from "@/data/downloads";

export default function ManagerPage() {
  return (
    <DownloadSystem
      title="下载 Manager"
      description="Telegram Bot 管理器客户端"
      builds={managerBuilds}
      product="Manager"
      num="01"
    />
  );
}

// pages/src/views/Manager.vue
<script setup lang="ts">
import DownloadSystem from "../components/DownloadSystem.vue"
import { managerBuilds } from "../data/downloads"
</script>

<template>
  <DownloadSystem
    title="下载 Manager"
    description="Telegram Bot 管理器客户端"
    :builds="managerBuilds"
    product="Manager"
    num="01"
  />
</template>
