// pages/src/app/service/page.tsx
import DownloadSystem from "@/components/DownloadSystem";
import { serviceBuilds } from "@/data/downloads";

export default function ServicePage() {
  return (
    <DownloadSystem
      title="下载 Service"
      description="服务端组件"
      builds={serviceBuilds}
      product="Service"
      num="02"
    />
  );
}

// pages/src/views/Service.vue
<script setup lang="ts">
import DownloadSystem from "../components/DownloadSystem.vue"
import { serviceBuilds } from "../data/downloads"
</script>

<template>
  <DownloadSystem
    title="下载 Service"
    description="服务端组件"
    :builds="serviceBuilds"
    product="Service"
    num="02"
  />
</template>
